#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  target_host=""
  target_device=""
  target_user=""
  target_port=""
  ssh_command=""
  ssh_options=()
  color=""
  quiet=""
}

_requirements() {
  local \
    _pkg="ssh"
  _check_cmd \
    "${_pkg}" \
    "open${_pkg}"
  _check_cmd \
    "mk${_pkg}config" \
    "${_pkg}-utils"
  _check_cmd \
    "hotspot-resolver"
}

_get_conf_path() {
  local \
    _dir \
    _conf
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  _conf="${_dir}/$( \
    _get \
      "target" \
      "host").cfg"
  echo \
    "${_conf}"
}

# Local ssh resolver
# $1: hostname of the device to connect
# $2: network device name
_dynssh() {
  local \
    _host="${1}" \
    _device="${2}" \
    _user="${3}" \
    _port="${4}" \
    _ssh_command="${5}" \
    _args=() \
    _msg=() \
    _sshcfg \
    _cfg \
    _hostname \
    _address="" \
    _ns
  shift \
    5
  _args=(
    "${@}"
  )
  _sshcfg="${HOME}/.cache/dynssh/ssh.config"
  mkdir \
    -p \
    "$(dirname \
         "${_sshcfg}")"
  _read_conf
  if [[ "${_port}" == "" ]]; then
    _port="$( \
      _read_settings \
        "$( \
          _get_conf_path \
            "${_host}" \
            "port")"
  fi
  _address="$( \
    hotspot-resolver \
      "${_hotspot_resolver_opts[@]}")"
  _msg=(
    "connecting to ${_user}@${_address}:${_port}"
    )
  _msg_info \
    "${_msg[*]}"
  rm \
    -f \
    "${_sshcfg}"
  mksshconfig \
    "${_sshcfg}" \
    "${_host}" \
    "${_address}" \
    "${_user}" \
    "${_port}"
  # _connection_test
  "${_ssh_command}" \
    -F "${_sshcfg}" \
    -o StrictHostKeyChecking=no \
    "${_args[@]}"
}

_connection_test() {
  if "${_ssh_command}" \
       -q \
       -F "${_sshcfg}" \
       -o StrictHostKeyChecking=no \
       -o ConnectTimeOut=5 \
       "${_host}" \
       'exit 0'; then
    return
  fi
  _msg_error \
    "can't connect to host '${_host}" \
    1
}

_make_conf() {
  mkdir \
    -p \
    "$(dirname \
         "$(_get_conf_path \
             "")")"
  echo \
    "# values go from 2 to 254" >> \
    "${_conf}"
  echo \
    "# device=111" >> \
    "${_conf}"
  [[ \
    "$( \
      command \
        -v \
        "hostnamectl")" != "" ]] && \
    _host="$( \
      hostnamectl \
        hostname)"
  _input_credentials
  _address="$( \
    _get_address \
      "${_device}")"
  echo \
    "${_host}=${_address##*.}:${_port}" >> \
    "${_conf}"
}

_check_conf() {
  local \
    _conf="${1}" \
    _address \
    _dir \
    _host \
    _port \
    _msg=() \
    _perm
  _dir="${HOME}/.config"
  _conf="${_dir}/${app_name}/localhosts.cfg"
  _msg=(
    "Configuration file:"
    "${_conf}"
  )
  _msg_info \
    "${_msg[*]}"
  if [ ! -e  "${_conf}" ]; then
    _make_conf
  fi
  _perm="$( \
    stat \
      -c '%a' \
      "${_conf}")"
  if [[ "${_perm}" != "700" ]]; then
    chmod \
      700 \
      "${_conf}"
  fi
}

_input_credentials() {
  if [[ "${_host}" == "" ]]; then
    printf \
      "  %s\n" \
      "enter name for this host:" && \
    while \
      [[ ! -v "_host" ]]; do
      read \
        -r \
        _host
    done
  fi
  printf \
    -v \
      "_port" \
    "%s\n" \
    "$( \
      _get \
        "target" \
        "port")"
  _msg_info \
    "setting local port as target port ${_port}"
  if \
    [[ \
      "${_port}" == "" ]]; then
    printf \
      "  %s\n" \
      "enter port for this host:"
    while \
      [[ \
        "${_port}" == "" ]]; do
      read \
        -r \
        _port
    done
  fi
  _msg_info \
    "Set port ${_port}"
}

_read_conf() {
  local \
    _conf \
    _dir \
    _hostname=""
  _dir="${HOME}/.config"
  _conf="${_dir}/${app_name}/localhosts.cfg"
  _check_conf \
    "${_conf}"
  _cfg="$( \
    cat \
      "${_conf}")"
  _cfg="$(\
    echo \
      "${_cfg}" | \
      sed \
        -e "/# */d" | \
	grep \
          "=" )"
  if [[ "${_cfg}" == '' ]]; then
    _msg_error \
      "empty configuration file!" \
      1
  fi
}

_set_overrides() {
  _set_override \
    "ssh" \
    "command" \
    "$( \
      command \
        -v \
        "ssh")"
  _set_override \
    "target" \
    "host" \
    ""
  _set_override \
    "target" \
    "device" \
    "wlan0"
  _set_override \
    "target" \
    "user" \
    "dev"
  _set_override \
    "target" \
    "port" \
    "2222"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
usage:
  $(_get "app" "name")
    [options]
    <host>
    [ssh options]
  options:
     -t <target_host>     Specify target host
     -d <device>          Specify network device
                          Default: '$(_get "target" "device")'
     -u <user>            user to connect to.
                          Default: '$(_get "target" "user")'
     -p <port>            Connect through a specific port.
                          Default: '$(_get "target" "port")'
     -C <ssh_path>        Connect using a specific ssh command.
                          Default: '$(_get "ssh" "command")'

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _build_date
  TZ=UTC \
    printf \
      -v _build_date \
      '%(%FT%R%z)T' \
      "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "          Connection date:   $(_get "_build" "date")"
  _msg_info "              SSH command:   $(_get "ssh" "command")"
  _msg_info "                     Host:   $(_get "target" "host")"
  _msg_info "                   Device:   $(_get "target" "device")"
  _msg_info "                     User:   $(_get "target" "user")"
  _msg_info "                     Port:   $(_get "target" "port")"
  if [[ "$(_get \
          "ssh" \
          "options")" != "" ]]; then
    _msg_info \
             "             SSH options:"
    _display_flags                        "${ssh_options[@]}"
  fi
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    't:d:u:p:C:cvh?' \
    arg; do
  case \
    "${arg}" in
    t) override_target_host="${OPTARG}" ;;
    d) override_target_device="${OPTARG}" ;;
    u) override_target_user="${OPTARG}" ;;
    p) override_target_port="${OPTARG}" ;;
    C) override_ssh_command="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
ssh_options=(
  "$@"
)
_set_overrides
[[ "$(_get \
        "target" \
        "host")" == "" ]] && \
  _msg_error \
   "-t option is required" \
   0 && \
  _usage \
   1
_show_config
_dynssh \
  "$( \
    _get \
      "target" \
      "host")" \
  "$( \
    _get \
      "target" \
      "device")" \
  "$( \
    _get \
      "target" \
      "user")" \
  "$( \
    _get \
      "target" \
      "port")" \
   "$( \
    _get \
      "ssh" \
      "command")" \
  "${ssh_options[@]}"

# vim:set sw=2 sts=-1 et:
